version: "3.8"
services:
    dbTest:
        image: "postgres:13"
        ports:
        - "5432:5432"
        volumes:
        - ./pgdata:/var/lib/postgresql/data
        environment:
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=admin2021
        - POSTGRES_DB=todoapp
    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080        